name: SafePtr Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package header-only library
      run: |
        mkdir package_out
        cp -r include package_out/include
        cp LICENSE package_out/
        cp README.md package_out/

    - uses: softprops/action-gh-release@v1
      with:
        files: |
          package_out/**
